In [1]:
import pandas as pd

In [ ]:
# Bring & Read Data
df = pd.read_excel(r"covid-19.xlsx")
df

,Date,Country_Region,Cases,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
0,2020-01-22,Afghanistan,0,0,0,0,0,0,0,Eastern Mediterranean
1,2020-01-22,Albania,0,0,0,0,0,0,0,Europe
2,2020-01-22,Algeria,0,0,0,0,0,0,0,Africa
3,2020-01-22,Andorra,0,0,0,0,0,0,0,Europe
4,2020-01-22,Angola,0,0,0,0,0,0,0,Africa
...,...,...,...,...,...,...,...,...,...,...
35151,2020-07-27,West Bank and Gaza,10621,78,3752,6791,152,2,0,Eastern Mediterranean
35152,2020-07-27,Western Sahara,10,1,8,1,0,0,0,Africa
35153,2020-07-27,Yemen,1691,483,833,375,10,4,36,Eastern Mediterranean
35154,2020-07-27,Zambia,4552,140,2815,1597,71,1,465,Africa
35155,2020-07-27,Zimbabwe,2704,36,542,2126,192,2,24,Africa

In [3]:
# Exploration Data Analysis
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35156 entries, 0 to 35155
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            35156 non-null  datetime64[ns]
 1   Country_Region  35156 non-null  object
 2   Cases           35156 non-null  int64
 3   Deaths          35156 non-null  int64
 4   Recovered       35156 non-null  int64
 5   Active          35156 non-null  int64
 6   New cases       35156 non-null  int64
 7   New deaths      35156 non-null  int64
 8   New recovered   35156 non-null  int64
 9   WHO Region      35156 non-null  object
dtypes: datetime64[ns](1), int64(7), object(2)
memory usage: 2.7+ MB

In [ ]:
df.sample(10)

,Date,Country_Region,Cases,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
32960,2020-07-16,Djibouti,4993,56,4796,141,8,0,31,Eastern Mediterranean
34124,2020-07-22,Kenya,14805,260,6757,7788,637,10,499,Africa
30118,2020-07-01,Bahamas,104,11,89,4,0,0,2,Americas
7858,2020-03-04,Angola,0,0,0,0,0,0,0,Africa
19916,2020-05-07,Laos,19,0,9,10,0,0,-1,Western Pacific
35093,2020-07-27,Nigeria,41180,860,18203,22117,648,2,829,Africa
33104,2020-07-17,Antigua and Barbuda,76,3,57,16,2,0,0,Americas
33252,2020-07-17,Somalia,3106,93,1444,1569,0,0,0,Eastern Mediterranean
3870,2020-02-11,Papua New Guinea,0,0,0,0,0,0,0,Western Pacific
11155,2020-03-21,Nicaragua,2,0,0,2,1,0,0,Americas

In [5]:
df.describe()

,Date,Cases,Deaths,Recovered,Active,New cases,New deaths,New recovered
count,35156,3.515600e+04,35156.000000,3.515600e+04,3.515600e+04,35156.00000,35156.000000,35156.000000
mean,2020-04-24 12:00:00,2.356663e+04,1234.068239,1.104813e+04,1.128443e+04,469.36375,18.603339,269.315593
min,2020-01-22 00:00:00,0.000000e+00,0.000000,0.000000e+00,-2.000000e+00,0.00000,-1918.000000,-16298.000000
25%,2020-03-08 18:00:00,1.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.00000,0.000000,0.000000
50%,2020-04-24 12:00:00,2.500000e+02,4.000000,3.300000e+01,8.500000e+01,2.00000,0.000000,0.000000
75%,2020-06-10 06:00:00,3.640250e+03,78.250000,1.286250e+03,1.454000e+03,75.00000,1.000000,20.000000
max,2020-07-27 00:00:00,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06,77255.00000,3887.000000,140050.000000
std,NaN,1.499818e+05,7437.238354,6.454640e+04,8.997149e+04,3005.86754,115.706351,2068.063852

In [15]:
# Print the number of empty or duplicate values
df.isnull().sum()

Date              0
Country_Region    0
Cases             0
Deaths            0
Recovered         0
Active            0
New cases         0
New deaths        0
New recovered     0
WHO Region        0
dtype: int64

In [7]:
print(f"Number of duplicate = {df.duplicated().sum()}")

Number of duplicate = 0

In [16]:
# Extract KPIs

Total_Cases = df['Cases'].sum()
print(f"Total Cases = {Total_Cases}")

Total_Deaths = df['Deaths'].sum()
print(f"Total Desths = {Total_Deaths}")

Total_Active = df['Active'].sum()
print(f"Total Active = {Total_Active}")

Total_Recovered = df['Recovered'].sum()
print(f"Total Recovered = {Total_Recovered}")

Deaths_Rate = Total_Deaths / Total_Cases
print(f"Deaths Rate = {Deaths_Rate}")

Recovery_Rate = Total_Recovered / Total_Cases
print(f"Recovery Rate = {Recovery_Rate}")

Total Cases = 828508482
Total Desths = 43384903
Total Active = 396715350
Total Recovered = 388408229
Deaths Rate = 0.0523650680018023
Recovery Rate = 0.4688041672939686

In [9]:
# Top 10 Counties Cases and Deaths as well as Continent
top10_Deaths_Countries = df.groupby('Country_Region')['Deaths'].sum().sort_values(ascending=False).head(10)
print(f"Top 10 Countries where Deaths : {top10_Deaths_Countries}")
print("-------------------")
top10_Cases_Countries = df.groupby('Country_Region')['Cases'].sum().sort_values(ascending=False).head(10)
print(f"Top 10 Countries where Cases : {top10_Cases_Countries}")

Top 10 Countries where Deaths : Country_Region
US                11011411
United Kingdom     3997775
Brazil             3938034
Italy              3707717
France             3048524
Spain              3033030
Mexico             1728277
India              1111831
Iran               1024136
Belgium             963679
Name: Deaths, dtype: int64
-------------------
Top 10 Countries where Cases : Country_Region
US                224345948
Brazil             89524967
Russia             45408411
India              40883464
Spain              27404045
United Kingdom     26748587
Italy              26745145
France             21210926
Germany            21059152
Iran               19339267
Name: Cases, dtype: int64

In [10]:
Cases_Continent = df.groupby('WHO Region')['Cases'].sum().sort_values(ascending=False)
print(f"Continent where Cases : {Cases_Continent}")
print("-------------------")
Deaths_Continent = df.groupby('WHO Region')['Deaths'].sum().sort_values(ascending=False)
print(f"Continent where Deaths : {Deaths_Continent}")

Continent where Cases : WHO Region
Americas                 402261194
Europe                   248879793
Eastern Mediterranean     74082892
South-East Asia           55118365
Western Pacific           26374411
Africa                    21791827
Name: Cases, dtype: int64
-------------------
Continent where Deaths : WHO Region
Americas                 19359292
Europe                   19271040
Eastern Mediterranean     1924029
South-East Asia           1458134
Western Pacific            932430
Africa                     439978
Name: Deaths, dtype: int64

In [11]:
# The rate of Cases, Deaths & Active over time
Cases_Over_Time = df.groupby('Date')['Cases'].sum()
print(f"Cases over time : {Cases_Over_Time}")

Cases over time : Date
2020-01-22         555
2020-01-23         654
2020-01-24         941
2020-01-25        1434
2020-01-26        2118
                ...
2020-07-23    15510481
2020-07-24    15791645
2020-07-25    16047190
2020-07-26    16251796
2020-07-27    16480485
Name: Cases, Length: 188, dtype: int64

In [12]:
Deaths_Over_Time = df.groupby('Date')['Deaths'].sum()
print(f"Deaths over time : {Deaths_Over_Time}")

Deaths over time : Date
2020-01-22        17
2020-01-23        18
2020-01-24        26
2020-01-25        42
2020-01-26        56
               ...
2020-07-23    633506
2020-07-24    639650
2020-07-25    644517
2020-07-26    648621
2020-07-27    654036
Name: Deaths, Length: 188, dtype: int64

In [13]:
Active_Over_Time = df.groupby('Date')['Active'].sum()
print(f"Active over time : {Active_Over_Time}")

Active over time : Date
2020-01-22        510
2020-01-23        606
2020-01-24        879
2020-01-25       1353
2020-01-26       2010
               ...
2020-07-23    6166006
2020-07-24    6212290
2020-07-25    6243930
2020-07-26    6309711
2020-07-27    6358362
Name: Active, Length: 188, dtype: int64

In [ ]:
df.to_excel(r"cleaned_covid-19.xlsx")